# Generated by Django 4.0.4 on 2022-04-28 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('creator_network', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)])),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('supply', models.CharField(blank=True, max_length=255, null=True)),
                ('royalties', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collection')),
            ],
        ),
    ]
